### ISSUE TITLE
changing directories in file selection with selectrum breaks annotations

### ISSUE THREAD

**Issue by ilohmar** [minad/marginalia#71] opened 2021-04-20 20:25 UTC
I start (a development build of) Emacs like this:
```
emacs -q -nw -l .config/emacs/elpa/marginalia-20210418.1718/marginalia.el -l .config/emacs/elpa/selectrum-20210327.1353/selectrum.el
```
and evaluate
```
(require 'selectrum) (require 'marginalia) (selectrum-mode) (marginalia-mode) (marginalia-cycle)
```
Now find-file gives me very nice annotations.  However, as soon as I change (TAB) into a sub-folder, or move out of one (C-M-Backspace), the annotations vanish.  The reason AFAICS is that the default-directory is not changed, so the partial file name cannot be resolved anymore.  Even worse, if a file/dir name in the new location happens to exist in the original location as well, the latter one's metadata is shown!

Note: I searched for this issue and found #12 and the associated discussions --- I got the impression that all of this had been sorted out already.  But it seems this was only for the case where one stays in the same directory all the time?

Is there anything obviously wrong with my setup, or, if not, are there any ideas how to improve the situation?

**Comment by oantolin** [comment] 2021-04-20 20:36
I can reproduce this in `emacs -Q` _with Selectrum_, but the annotations work just fine with default completion (and thus also with Vertico, icomplete-vertical and Embark live collect). I'm guessing the problem is with our new implementation of `marginalia--full-candidate`, which we probably just did not test on Selectrum. I'll look into it.

**Comment by ilohmar** [comment] 2021-04-20 20:43
Awesome.  Yes, you're absolutely right, I just haven't used the default completion for.. decades, so it did not even occur to me to check that.  I will amend the title.

**Comment by oantolin** [comment] 2021-04-20 21:15
So 7fe1a031735be6a4d6ed97601b857b29a7264c30 fixes this (please test when you get the chance), but I'm not too happy that I used an internal Selectrum function to do it. @minad, maybe you see how to fix this without `selectrum--get-full`?

**Comment by minad** [comment] 2021-04-20 21:21
I have no idea unfortunately. While I understand how the "core functionality" of Selectrum works, I have no idea of the additional read functions (read file, read buffer etc). We have to summon @clemera for this. Maybe there is a better way, but I am not overly worried about this small special case for Selectrum.

**Comment by ilohmar** [comment] 2021-04-20 21:39
I agree that it would be even nicer to not rely on selectrum internals, but for what it's worth, it works smoothly for me!  Thanks a lot!

**Comment by minad** [comment] 2021-04-21 15:08
It seems to work, but I think there is a Selectrum bug with partial completion.

**Comment by minad** [comment] 2021-04-21 15:09
Closing, since it should be fixed.

**Closed by minad** 2021-04-21 15:09 UTC
