### ISSUE TITLE
Annotations truncated on the right

### ISSUE THREAD

**Issue by smsegal** [minad/marginalia#38] opened 2020-12-24 17:40 UTC
Hello, 

I'm using the combination of selectrum+consult+marginalia. 
When I have consult-preview-mode and use the heavy annotations as default, I get the following output for finding files:
![marginalia-selectrum](https://user-images.githubusercontent.com/7110093/103101155-48224e80-45e4-11eb-8c35-1fb3811b9839.png)
As you can see, there is plenty of available space for the annotations to be displayed fully, but the date is truncated with a `$`. 

A similar issue occurs with `M-x` and other annotated commands: 
![marginalia-Mx](https://user-images.githubusercontent.com/7110093/103101287-e3b3bf00-45e4-11eb-991e-adce590c3704.png)
Here, the descriptions aren't truncated, but still have the line continuation symbol `$` present. 

Is there a configuration option I'm missing or some other easy fix for this? 

For reference, I'm on Emacs28 with native-comp:
`GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-12-05`

Thanks!

**Comment by minad** [comment] 2020-12-24 20:19
Looks as if everything is just off by a single character. I am not seeing this on Emacs 27.1. Can you test with emacs -Q? Can you also test on a stable Emacs on your system for comparison?

**Comment by smsegal** [comment] 2021-01-01 16:41
Got distracted by the holidays on this one :) 

I found the problem here, I was using the built-in fringe package and calling `(set-fringe-style 0)`. This sets the pixel width of the fringes to 0 and seems to affect the display of the marginalia. Setting the fringe style to the default ( `(set-fringe-style nil)` or just not touching it) fixes the problem.

**Comment by minad** [comment] 2021-01-01 16:58
@smsegal Thank you! So this is not a bug in marginalia and I close this here. If you have a suggestion on how to improve the default width computation, feel free to open a separate issue! But I am not willing to accept a significant increase in complexity to work around special (potentially bad?) config settings.

**Closed by minad** 2021-01-01 16:58 UTC

**Comment by azzamsa** [comment] 2021-01-05 09:18
It still happening on my end.

![image](https://user-images.githubusercontent.com/17734314/103628356-75221a00-4f71-11eb-8ed1-4c87f34b65a9.png)

```lisp
(use-package marginalia
  :after consult
  :init
  (marginalia-mode)
  (set-fringe-style nil)
)
```

GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-12-28

**Comment by minad** [comment] 2021-01-05 11:27
@azzamsa See #42. @terlar is trying to find a more robust alignment specification.

**Comment by azzamsa** [comment] 2021-01-05 11:48
I've tried `(setq fringes-outside-margins nil)` and `(setq fringes-outside-margins t)`, nothing works.

I've also tried to include `left-margin-width` and `right-margin-width`

``` elisp

( use-package marginalia
  :after consult
  :init
  (marginalia-mode)

  (setq fringes-outside-margins nil)
  (setq left-margin-width 1)
  (setq right-margin-width 1)
  
  )

```

**Comment by minad** [comment] 2021-01-05 12:14
@azzamsa This will be sorted out, see #42. Did you try the proposed changes from there? This would help!

**Comment by azzamsa** [comment] 2021-01-05 14:05
Thanks a lot @minad, [solved](https://github.com/minad/marginalia/issues/42#issuecomment-754655574)
