### ISSUE TITLE
marginalia-annotate-buffer makes it difficult to distinguish between similarly named buffers

### ISSUE THREAD

**Issue by robbert-vdh** [minad/marginalia#99] opened 2021-08-07 13:32 UTC
Hi! I recently switched to Vertico & friends after Doom added a module for it. It's been a great experience so far, but I noticed a couple of minor things that could maybe use some polish. When switching between buffers (e.g. using `consult-buffer`), the last column now shows the full path to a file (or relative to the home directory). This makes it impossible to visually distinguish between similarly named files, because the last components of the file's path will always be truncated (this column seems to have a fixed width, resizing the frame doesn't make it grow any wider). The formatting for this is done [here](https://github.com/minad/marginalia/blob/11235445365c6ab119acabe91828e9182097ece7/marginalia.el#L749-L765). In contrast, `ivy-rich` strips away the project root when showing these paths, making it much easier to see where the file backing the buffer is coming from. Would it be possible to get something similar in marginalia as an option? For reference, this is what it looks like currently:

![afbeelding](https://user-images.githubusercontent.com/748520/128601576-9cf48097-2e2f-4e81-a59f-5b9e4c159d73.png)

**Comment by minad** [comment] 2021-08-07 13:36
Thanks for the suggestion! This is mostly a duplicate of #70.

**Closed by minad** 2021-08-07 13:36 UTC
