### ISSUE TITLE
How remove lines?

### ISSUE THREAD

**Issue by alexei-28** [minad/marginalia#102] opened 2021-08-31 09:15 UTC
LInux Mint 20.2.
Emacs 27.1

I installed package marginalia ver. 0.8.
In my **init.el**

`(require 'marginalia)`

Restart Emacs. And here result:

![Screenshot from 2021-08-31 12-13-45](https://user-images.githubusercontent.com/303539/131476447-0bf9a330-8335-4ceb-8a9c-ef3a6b3f3ad6.png)

The question is: How remove this lines?

**Comment by minad** [comment] 2021-09-04 11:15
> The question is: How remove this lines?

By changing or fixing the theme. You may want to give the modus themes a try, in particular the dark `modus-vivendi`.

Closing since it is not a Marginalia issue.

**Closed by minad** 2021-09-04 11:15 UTC

**Comment by alexei-28** [comment] 2021-09-04 14:51
> > The question is: How remove this lines?
> 
> By changing or fixing the theme. You may want to give the modus themes a try, in particular the dark `modus-vivendi`.
> 
> Closing since it is not a Marginalia issue.

I changed my color theme
from

` '(custom-enabled-themes '(wheatgrass))`

to
` '(custom-enabled-themes '(tango-dark))`


but it not help.
Same result
![Screenshot from 2021-09-04 17-48-25](https://user-images.githubusercontent.com/303539/132098565-71b5765c-5ead-4a79-bd87-3ff44cb8713e.png)

**Comment by minad** [comment] 2021-09-04 14:55
Can you reproduce this with emacs -Q?

**Comment by alexei-28** [comment] 2021-09-04 16:46
> Can you reproduce this with emacs -Q and only vertico+marginalia+theme?

1. I installed **marginalia** on the another laptop with the same Emacs's settings (same theme and so on). As result no lines

**Comment by alexei-28** [comment] 2021-09-04 18:50
> > The question is: How remove this lines?
> 
> By changing or fixing the theme. You may want to give the modus themes a try, in particular the dark `modus-vivendi`.
> 
> Closing since it is not a Marginalia issue.

After I install package **modus-theme** the problem is gone.

In my init.el file:

```
;; https://protesilaos.com/modus-themes/
(require 'modus-themes)
(load-theme 'modus-operandi) ; Light theme
(load-theme 'modus-vivendi)  ; Dark theme
;; Load the theme files before enabling a theme (else you get an error).
(modus-themes-load-themes)

```

![Screenshot from 2021-09-04 21-47-49](https://user-images.githubusercontent.com/303539/132105104-95b1337b-11ef-47dc-94c1-b9d8c6f6662e.png)
